title: Play your avatar
description: Upload your avatar choose a game and play
theme: jekyll-theme-8bit
logo: nes-kirby
show_avatar: true
show_posts: true
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 3
paginate_path: "/blog/page:num"
social:
  twitter: https://twitter.com/username
  facebook: https://facebook.com/username
  github: https://github.com/username
  youtube: https://youtube.com/channel/ID
  google: https://plus.google.com/username
  medium: https://medium.com/@username
  twitch: https://twitch.com/username
  reddit: https://www.reddit.com/user/username
  whatsapp: tel:+5541999999999
  gmail: mailto:username@domain.net
  linkedin: https://www.linkedin.com/in/username
disqus:
  shortname: jekyll-theme-8bit
